# Generated by Django 6.0.6 on 2026-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='department_assigned_to',
        ),
        migrations.AddField(
            model_name='document',
            name='current_holder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='municipal_stamp',
            field=models.ImageField(blank=True, upload_to='stamps/'),
        ),
        migrations.AddField(
            model_name='document',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_registry_review', 'Under Registry Review'), ('registered', 'Registered'), ('forwarded_to_dept', 'Forwarded to Department'), ('under_dept_review', 'Under Department Review'), ('awaiting_director', 'Awaiting Director Approval'), ('approved', 'Approved'), ('returned_to_registry', 'Returned to Registry'), ('ready_for_collection', 'Ready for Collection'), ('collected', 'Collected')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('registry', 'Registrar'), ('department', 'Department Officer'), ('director', 'Director'), ('applicant', 'Applicant')], default='applicant', max_length=20),
        ),
    ]
