# Generated by Django 6.0.6 on 2026-07-29 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_notification_is_read_notification_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='certified_file',
            field=models.FileField(blank=True, help_text='Stamped PDF with QR overlay + signature metadata', upload_to='certified/'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 hex digest of the uploaded file at time of signing', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='integrity_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last time integrity check passed', null=True),
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('RSA-PSS-SHA256', 'RSA-PSS SHA-256')], default='RSA-PSS-SHA256', max_length=30)),
                ('document_hash', models.CharField(editable=False, help_text='SHA-256 hex of the file', max_length=64)),
                ('signature_value', models.TextField(editable=False, help_text='Hex-encoded RSA-PSS signature')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(blank=True, help_text='Last verification result', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_fingerprint', models.CharField(blank=True, help_text='SHA-256 of public key PEM', max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signatures', to='documents.document')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
