# Generated by Django 6.0.6 on 2026-07-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_certified_file_document_document_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_signed_file',
            field=models.FileField(blank=True, help_text='Externally signed PDF uploaded by Director for cross-check', upload_to='external_signed/'),
        ),
    ]
